let gamesList = [
    {
        name: "The Last of Us II",
        title: "Cinco anos depois da jornada perigosa pelos Estados Unidos pós-pandêmicos, Ellie e Joel se estabelecem em Jackson, Wyoming",
        platform: "PlayStation",
        price: 100.00,
        imagem: "img/The_Last_of_Us_II.jpg",
    },
    {
        name: "Horizon Forbidden West",
        title: "A terra está morrendo; tempestades implacáveis e uma praga incontrolável devastam o que sobrou da humanidade enquanto máquinas assustadoras vagam por territórios próximos",
        platform: "PlayStation",
        price: 186.00,
        imagem: "img/Horizon_Forbidden_West.jpg",
    },
    {
        name: "Red Dead Redemption 2",
        title: "Os que não se rendem, nem sucumbem, são mortos. Viva a magia do faroeste na continuação mais aguarda da Rockstar",
        platform: "PlayStation",
        price: 109.83,
        imagem: "img/Red_Dead_Redemption_2.jpg",
    },
    {
        name: "God of War Ragnarök",
        title: "Embarque em uma jornada épica e comovente onde Kratos e Atreus lutam entre o desejo de manterem-se unidos ou separar-se. Derrote deuses e monstros nórdicos em combates fluidos e expressivos",
        platform: "PlayStation",
        price: 246.31,
        imagem: "img/God_of_War_Ragnarok.jpg",
    },
    {
        name: "Elden Ring",
        title: "Exploração do mundo nas Terras Intermédias: ELDEN RING apresenta vastos cenários fantásticos e complexas e escuras masmorras que se conectam de maneira fluida",
        platform: "PlayStation",
        price: 199.99,
        imagem: "img/Elden_Ring.jpg",
    },
    {
        name: "Ghost of Tsushima",
        title: "Na tsushima devastada, uma beleza ancestral resiste. Mostre todo o seu poder samurai para todo Japão Feudal",
        platform: "PlayStation",
        price: 154.99,
        imagem: "img/Ghost_of_Tsushima.jpg",
    },
    {
        name: "Assassin’s Creed Valhalla",
        title: "Crie e personalize um guerreiro viking único dentro do seu clã e compartilhe online com amigos para que usem nas invasões deles",
        platform: "Xbox",
        price: 109.00,
        imagem: "img/Assassin’s_Creed_Valhalla.jpg",
    },
    {
        name: "Resident Evil Village",
        title: "Ethan e Mia Winters estão reunidos e colocando seus pesadelos compartilhados na plantação do Baker para trás.até que sua vida seja destruída e Ethan se torne o ponto focal de um novo tormento",
        platform: "Xbox",
        price: 173.90,
        imagem: "img/Resident_Evil_Village.jpg",
    },
    {
        name: "Dying Light 2 Stay Human",
        title: "Espere pela noite para adentrar os sombrios esconderijos dos Infectados e mate quantos puder o quanto antes",
        platform: "Xbox",
        price: 209.90,
        imagem: "img/Dying_Light_2_Stay_Human.jpg",
    },
    {
        name: "FIFA 21",
        title: "Vença como um time no FIFA 21 com novas maneiras de jogar e se expressar nas ruas e nos estádios",
        platform: "Xbox",
        price: 201.90,
        imagem: "img/FIFA_21.jpg",
    },
    {
        name: "Marvel’s Guardians Of The Galaxy",
        title: "Uma nova história: seu recém-formado grupo de desajustados lendários está determinado a salvar o universo nesta nova e fiel versão dos guardiões da galáxia",
        platform: "Xbox",
        price: 143.84,
        imagem: "img/Marvel’s_Guardians_Of_The_Galaxy.jpg",
    },
    {
        name: "Super Mario Maker 2",
        title: "Super Mario Maker 2 é um jogo eletrônico de plataforma e editor de mapas",
        platform: "Switch",
        price: 344.89,
        imagem: "img/Super_Mario_Maker_2.jpg",
    },
    {
        name: "The Legend Of Zelda: Breath Of The Wild",
        title: "Explore hyrule com total liberdade como jamais visto. Mostre todo o seu potencial élfico defendendo quem você ama a todo custo",
        platform: "Switch",
        price: 348.89,
        imagem: "img/The_Legend_Of_Zelda_Breath_Of_The_Wild.jpg",
    },
    {
        name: "Pokémon Legends: Arceus",
        title: "Ação e RPG encontram-se à medida que a série Pokémon atinge uma nova fronteira",
        platform: "Switch",
        price: 339.89,
        imagem: "img/Pokémon_Legends_Arceus.jpg",
    },
    {
        name: "Super Smash Bros Ultimate",
        title: "Novos lutadores, como Inkling da série Splatoon e Ridley da série Metroid, fazem sua estréia na série Super Smash Bros. ao lado de todos os lutadores Super Smash Bros. da série!",
        platform: "Switch",
        price: 343.89,
        imagem: "img/Super_Smash_Bros_Ultimate.jpg",
    },
    {
        name: "Assassin's Creed IV Black Flag",
        title: "O ano é 1715. Os piratas governam o Caribe e estabeleceram sua própria República sem lei, onde a corrupção, a ganância e a crueldade são comuns. Entre esses bandidos está um jovem capitão impetuoso chamado Edward Kenway",
        platform: "PC",
        price: 34.99,
        imagem: "img/Assassins_Creed_IV_Black_Flag.jpg",
    },
    {
        name: "Stock Car",
        title: "O Game Stock Car oferece aos jogadores a experiência de pilotar e competir virtualmente a bordo de um bólido modelo JL G-09, usado por todas as equipes da categoria, enquanto simula a temporada 2010 com 34 pilotos e 10 pistas meticulosamente modeladas como o autódromo de Interlagos em São Paulo",
        platform: "PC",
        price: 69.90,
        imagem: "img/Stock_Car.jpg",
    },
    {
        name: "Assassin's Creed Odyssey",
        title: "Continue sua odisseia épica com duas grandes e novas histórias, cada uma com três episódios emocionantes",
        platform: "PC",
        price: 74.99,
        imagem: "img/Assassin's_Creed_Odyssey.jpg",
    },
    {
        name: "Far Cry 3",
        title: "Além dos limites da civilização existe uma ilha, uma terra sem lei dominada pela violência e sofrimento humano, de onde só se escapa pelas drogas ou pelo cano de uma arma",
        platform: "PC",
        price: 59.99,
        imagem: "img/Far_Cry_3.jpg",
    },
];